-- CourseConnect Oracle relational schema
-- Run as a coursework user in Oracle SQL Developer.

BEGIN
  FOR t IN (
    SELECT table_name
    FROM user_tables
    WHERE table_name IN (
      'USERS', 'CERTIFICATES', 'LESSON_PROGRESS', 'PAYMENTS', 'ENROLLMENTS',
      'LESSONS', 'COURSES', 'STUDENTS', 'LECTURERS', 'CATEGORIES'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

CREATE TABLE categories (
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR2(80) NOT NULL UNIQUE,
  description VARCHAR2(300)
);

CREATE TABLE lecturers (
  lecturer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(120) NOT NULL,
  email VARCHAR2(160) NOT NULL UNIQUE,
  expertise VARCHAR2(120) NOT NULL,
  joined_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT ck_lecturer_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE students (
  student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(120) NOT NULL,
  email VARCHAR2(160) NOT NULL UNIQUE,
  registered_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT ck_student_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'GRADUATED'))
);

CREATE TABLE courses (
  course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id NUMBER NOT NULL,
  lecturer_id NUMBER NOT NULL,
  course_title VARCHAR2(160) NOT NULL,
  course_level VARCHAR2(40) NOT NULL,
  price NUMBER(10,2) NOT NULL,
  duration_hours NUMBER(5,1) NOT NULL,
  published_status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
  created_date DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_course_category FOREIGN KEY (category_id) REFERENCES categories(category_id),
  CONSTRAINT fk_course_lecturer FOREIGN KEY (lecturer_id) REFERENCES lecturers(lecturer_id),
  CONSTRAINT ck_course_price CHECK (price >= 0),
  CONSTRAINT ck_course_status CHECK (published_status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE lessons (
  lesson_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id NUMBER NOT NULL,
  lesson_title VARCHAR2(160) NOT NULL,
  lesson_order NUMBER NOT NULL,
  estimated_minutes NUMBER DEFAULT 30 NOT NULL,
  CONSTRAINT fk_lesson_course FOREIGN KEY (course_id) REFERENCES courses(course_id),
  CONSTRAINT uq_lesson_order UNIQUE (course_id, lesson_order)
);

CREATE TABLE enrollments (
  enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id NUMBER NOT NULL,
  course_id NUMBER NOT NULL,
  enrollment_date DATE DEFAULT SYSDATE NOT NULL,
  enrollment_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  completion_percent NUMBER(5,2) DEFAULT 0 NOT NULL,
  final_score NUMBER(5,2),
  CONSTRAINT fk_enroll_student FOREIGN KEY (student_id) REFERENCES students(student_id),
  CONSTRAINT fk_enroll_course FOREIGN KEY (course_id) REFERENCES courses(course_id),
  CONSTRAINT uq_student_course UNIQUE (student_id, course_id),
  CONSTRAINT ck_enroll_status CHECK (enrollment_status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT ck_completion CHECK (completion_percent BETWEEN 0 AND 100)
);

CREATE TABLE payments (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id NUMBER NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  payment_method VARCHAR2(30) NOT NULL,
  payment_status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  paid_date DATE,
  transaction_ref VARCHAR2(80) UNIQUE,
  CONSTRAINT fk_payment_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id),
  CONSTRAINT ck_payment_amount CHECK (amount >= 0),
  CONSTRAINT ck_payment_status CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED'))
);

CREATE TABLE lesson_progress (
  progress_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id NUMBER NOT NULL,
  lesson_id NUMBER NOT NULL,
  completed_flag CHAR(1) DEFAULT 'N' NOT NULL,
  completed_date DATE,
  quiz_score NUMBER(5,2),
  CONSTRAINT fk_progress_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id),
  CONSTRAINT fk_progress_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(lesson_id),
  CONSTRAINT uq_progress_lesson UNIQUE (enrollment_id, lesson_id),
  CONSTRAINT ck_completed_flag CHECK (completed_flag IN ('Y', 'N')),
  CONSTRAINT ck_quiz_score CHECK (quiz_score BETWEEN 0 AND 100)
);

CREATE TABLE certificates (
  certificate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id NUMBER NOT NULL UNIQUE,
  issued_date DATE DEFAULT SYSDATE NOT NULL,
  certificate_code VARCHAR2(40) NOT NULL UNIQUE,
  CONSTRAINT fk_certificate_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id)
);

-- Application login accounts (added for the web app layer: role-based
-- access for admins, lecturers, and students on top of the core schema).
CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR2(160) NOT NULL UNIQUE,
  full_name VARCHAR2(120) NOT NULL,
  role VARCHAR2(20) NOT NULL,
  password_hash VARCHAR2(200) NOT NULL,
  password_salt VARCHAR2(64) NOT NULL,
  linked_lecturer_id NUMBER,
  linked_student_id NUMBER,
  CONSTRAINT ck_user_role CHECK (role IN ('ADMIN', 'LECTURER', 'STUDENT')),
  CONSTRAINT fk_user_lecturer FOREIGN KEY (linked_lecturer_id) REFERENCES lecturers(lecturer_id),
  CONSTRAINT fk_user_student FOREIGN KEY (linked_student_id) REFERENCES students(student_id)
);

CREATE INDEX idx_courses_category ON courses(category_id);
CREATE INDEX idx_courses_lecturer ON courses(lecturer_id);
CREATE INDEX idx_enrollments_student ON enrollments(student_id);
CREATE INDEX idx_enrollments_course ON enrollments(course_id);
CREATE INDEX idx_payments_status ON payments(payment_status);
